### ISSUE TITLE
COOKIES

### ISSUE THREAD

**Issue by GCDevExchange-CarrefourProgGC** [canada-ca/commons#3]
Value: $500.00Closes: Friday, January 12, 2018Location:  Some in-person work required<h2>Opportunity Description</h2><p>Chocolate, flower, eggs and baking soda.</p><h2>Acceptance Criteria</h2><p>Cookies must be soft and chewy.</p><h2>How to Apply</h2><p>Go to the <a href="https://gcdevexchange-carrefourproggc.org/opportunities/opp-cookies">Opportunity Page</a>, click the Apply button above and submit your proposal by 16:00 PST on Friday, January 12, 2018</b>.</p><p>We plan to assign this opportunity by <b>Friday, January 12, 2018</b> with work to start on <b>Friday, January 12, 2018</b>.</p><h2>Proposal Evaluation Criteria</h2><p>This is a test proposal.</p>

**Comment by RachelMuston** [comment]
This issue was created as a test of the GC Developers Exchange.
